# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dfd1b089df3bb20342af9b9eda37e563"
name = "wishlist-text"
handle = "wishlist-text"
application_url = "https://grant-examines-ashley-mg.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://grant-examines-ashley-mg.trycloudflare.com/auth/callback", "https://grant-examines-ashley-mg.trycloudflare.com/auth/shopify/callback", "https://grant-examines-ashley-mg.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
